baseURL = 'https://0xf4h3d.github.io/'
languageCode = 'en-us'
title = "fahed's website "
theme = "archie"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/0xf4h3d"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ul3n/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/fahad-almarhabi-a727b9205/"

paginate=4